name: Frontend CI (Vite + React + TS)

on:
  push:
    branches: [main]

jobs:
  frontend-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint code (ESLint)
        run: npm run lint

      - name: Format with Prettier
        run: |
          npx prettier --write .

      - name: Build the project (Vite)
        run: npm run build
